apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coursegen-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: coursegen.local
      http:
        paths:
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: coursegen-service
                port:
                  number: 4000
